### ISSUE TITLE
Quantify Extension: Decreasing Quantity on Numeric Input

### ISSUE THREAD

**Issue by mailelucks** [mivaecommerce/readytheme-shadows#59] opened 2019-01-14 19:52 UTC
Provide a general summary of the issue in the Title above

## Expected Behavior
When pressing enter, the value in the input box should be saved

## Current Behavior
When pressing enter, the quantity decreases by 1

## Attempted Fixes
None as of yet, I believe it should be addressed in the js file directly vs coding on top of it.

## Steps to Reproduce (for bugs)
Noticed during build, try playing around with the quantity input box:

https://nationalworkwear.mivamerchant.net/miva-test-product-5-aenean-tincidunt-quam-ut-convallis-lacinia-donec-eleifend-semper-nisl-et-blandi.html

Bug is also affecting BASK.

## Context
UX issue, sometimes on BASK it will clear out the entire line item completely.

## Your Environment
osHighSierra, Chrome 71

**Comment by influxweb** [comment] 2019-01-15 16:57
When you say "the value in the input box should be saved", what is the expected functionality? Should nothing happen?

From the standpoint of usability and accessibility, that is the expected function. Once the button has focus, the `enter` key or `spacebar` will continue to modify the quantity until something changes the focus away from the button.

I will leave this issue open for now in case there are any reports of issues in the wild.

**Comment by influxweb** [comment] 2019-01-15 18:50
@steveosoule - I was able to reproduce the issue when dealing with the plus and minus buttons, however I am not convinced it is an actual bug as the functionality is expected when using the keyboard for navigation. As for what happens when you use `enter` in the input itself, I will investigate that.

**Comment by influxweb** [comment] 2019-01-16 18:02
Since there is no `action` being passed to the Quantify function on initial page load, the `Enter` key seems to trigger the `decrement` action. To prevent this, I have added a listener for `keydown` events in the function.

I have added this enhancement and it will be included in the next maintenance release. To make the update prior to the next release, you will need to update the contents of **`User Interface -> JavaScript Resources -> quantify`** with the following:

```javaascript
/**
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |q|u|a|n|t|i|f|y|
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *
 * This extension allows for the use of buttons to increase/decrease item
 * quantities on the product and basket pages. When used on the basket page,
 * the decrease button becomes a remove button if the quantity is 1.
 */

(function () {
	'use strict';

	var adjusters = document.querySelectorAll('[data-hook="quantify"]');

	for (var id = 0; id < adjusters.length; id++) {
		/**
		 * This listener prevents the `enter` key from adjusting the `input` value.
		 */
		adjusters[id].addEventListener('keydown', function (keyEvent) {
			if (keyEvent.target.matches('input')) {
				if (keyEvent.key === 'Enter') {
					keyEvent.preventDefault();
				}
			}
		});

		adjusters[id].addEventListener('click', function (event) {
			if (event.target.matches('button')) {
				var button = event.target;
				var inputs = [].filter.call(this.children, function (sibling) {
					return sibling !== button && sibling.matches('input');
				});
				var input = inputs[0];
				var value = parseInt(input.value);
				var action = button.getAttribute('data-action');
				var changed = document.createEvent('HTMLEvents');
				var groupForm = document.querySelector('[data-hook="' + input.getAttribute('data-group') + '"]');

				changed.initEvent('change', true, false);
				event.stopPropagation();
				event.preventDefault();

				if (action === 'decrement') {
					/**
					 * THIS CAN BE USED TO SET A MINIMUM QUANTITY
					 * value = value > 5 ? value - 1 : 5;
					 */
					value = value > 1 ? value - 1 : 1;

					input.value = value;
					input.dispatchEvent(changed);
					allowRemoveUpdate();
				}
				else if (action === 'increment') {
					/**
					 * THIS CAN BE USED TO SET A MAXIMUM QUANTITY
					 * value = value < 100 ? value + 1 : 100;
					 */
					value = value + 1;

					input.value = value;
					if (groupForm) {
						groupForm.elements['Action'].value = 'QTYG';
					}
					input.dispatchEvent(changed);
					allowRemoveUpdate();
				}
				else {
					console.log('test');
					input.value = 0;
					input.dispatchEvent(changed);
				}
			}
		});
	}

	function allowRemoveUpdate() {
		var quantities = document.querySelectorAll('[data-hook="group-quantity"]');

		if (quantities) {
			for (var id = 0; id < quantities.length; id++) {
				var quantityLine = quantities[id];
				var removeToggle = quantityLine.previousElementSibling;
				var groupForm = document.querySelector('[data-hook="' + quantityLine.getAttribute('data-group') + '"]');

				if (removeToggle.dataset.hook !== 'remove') {
					if (quantityLine.value > '1') {
						if (groupForm) {
							groupForm.elements['Action'].value = 'QTYG';
						}
						removeToggle.classList.remove('u-icon-remove');
						removeToggle.classList.add('u-icon-subtract');
						removeToggle.setAttribute('data-action', 'decrement');
					}
					else {
						if (groupForm) {
							groupForm.elements['Action'].value = 'RGRP';
						}
						removeToggle.classList.remove('u-icon-subtract');
						removeToggle.classList.add('u-icon-remove');
						removeToggle.setAttribute('data-action', 'remove');
					}
				}

				quantityLine.addEventListener('change', function (event) {
					groupSubmit(event, this);
				});

				quantityLine.addEventListener('input', function (event) {
					groupSubmit(event, this);
				});
			}
		}
	}

	allowRemoveUpdate();

	function groupSubmit(event, quantity) {
		if (event.key !== 8 && event.key !== 37 && event.key !== 38 && event.key !== 39 && event.key !== 40 && event.key !== 46 && quantity.value !== '') {
			document.querySelector('[data-hook="' + event.target.getAttribute('data-group') + '"]').submit();
		}
	}
})();
```

**Comment by mailelucks** [comment] 2019-04-16 20:12
Hi Matt,

I have discovered a new issue with this script.

1 ) If updating the quantity in basket from "1", the action is defaulting to "data-remove" even if you are appending numbers to the "1" or changing the "1" to any other number.
2) If you update the quantity using the increment button, the quantity will correctly increase. After updating, the quantity input will work as intended.

To rephrase, if the quantity is "1", the action defaults to remove. If the quantity is anything else, it works as intended.

Feel free to contact me with any additional questions.

Thanks!

**Comment by influxweb** [comment] 2019-04-16 22:14
Since the current value was being used to determine the update state of the form, it would cause this functionality when the quantity is "1". I have added an additional check which will take the input to determine what to do next.

I have updated this enhancement and it will be included in the next maintenance release. To make the update prior to the next release, you will need to update the contents of **`User Interface -> JavaScript Resources -> quantify`** with the following:

```javascript
/**
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |q|u|a|n|t|i|f|y|
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *
 * This extension allows for the use of buttons to increase/decrease item
 * quantities on the product and basket pages. When used on the basket page,
 * the decrease button becomes a remove button if the quantity is 1.
 */

(function () {
	'use strict';

	var adjusters = document.querySelectorAll('[data-hook="quantify"]');

	for (var id = 0; id < adjusters.length; id++) {
		/**
		 * This listener prevents the `enter` key from adjusting the `input` value.
		 */
		adjusters[id].addEventListener('keydown', function (keyEvent) {
			if (keyEvent.target.matches('input')) {
				if (keyEvent.key === 'Enter') {
					keyEvent.preventDefault();
				}
			}
		});

		adjusters[id].addEventListener('click', function (event) {
			if (event.target.matches('button')) {
				var button = event.target;
				var inputs = [].filter.call(this.children, function (sibling) {
					return sibling !== button && sibling.matches('input');
				});
				var input = inputs[0];
				var value = parseInt(input.value);
				var action = button.getAttribute('data-action');
				var changed = document.createEvent('HTMLEvents');
				var groupForm = document.querySelector('[data-hook="' + input.getAttribute('data-group') + '"]');

				changed.initEvent('change', true, false);
				event.stopPropagation();
				event.preventDefault();

				if (action === 'decrement') {
					/**
					 * THIS CAN BE USED TO SET A MINIMUM QUANTITY
					 * value = value > 5 ? value - 1 : 5;
					 */
					value = value > 1 ? value - 1 : 1;

					input.value = value;
					input.dispatchEvent(changed);
					allowRemoveUpdate();
				}
				else if (action === 'increment') {
					/**
					 * THIS CAN BE USED TO SET A MAXIMUM QUANTITY
					 * value = value < 100 ? value + 1 : 100;
					 */
					value = value + 1;

					input.value = value;
					if (groupForm) {
						groupForm.elements['Action'].value = 'QTYG';
					}
					input.dispatchEvent(changed);
					allowRemoveUpdate();
				}
				else {
					input.value = 0;
					input.dispatchEvent(changed);
				}
			}
		});
	}

	function allowRemoveUpdate() {
		var quantities = document.querySelectorAll('[data-hook="group-quantity"]');

		function toggleRemove(row, qty) {
			var removeToggle = row.previousElementSibling;
			var groupForm = document.querySelector('[data-hook="' + row.getAttribute('data-group') + '"]');

			if (removeToggle.dataset.hook !== 'remove') {
				if (qty > '1') {
					if (groupForm) {
						groupForm.elements['Action'].value = 'QTYG';
					}
					removeToggle.classList.remove('u-icon-remove');
					removeToggle.classList.add('u-icon-subtract');
					removeToggle.setAttribute('data-action', 'decrement');
				}
				else if (qty === '1') {
					if (groupForm) {
						groupForm.elements['Action'].value = 'QTYG';
					}
					removeToggle.classList.remove('u-icon-subtract');
					removeToggle.classList.add('u-icon-remove');
					removeToggle.setAttribute('data-action', 'remove');
				}
				else {
					if (groupForm) {
						groupForm.elements['Action'].value = 'RGRP';
					}
					removeToggle.classList.remove('u-icon-subtract');
					removeToggle.classList.add('u-icon-remove');
					removeToggle.setAttribute('data-action', 'remove');
				}
			}
		}

		if (quantities) {
			for (var id = 0; id < quantities.length; id++) {
				var quantityLine = quantities[id];

				toggleRemove(quantityLine, quantityLine.value);

				quantityLine.addEventListener('change', function (event) {
					toggleRemove(this, this.value);
					groupSubmit(event, this);
				});

				quantityLine.addEventListener('input', function (event) {
					toggleRemove(this, this.value);
					groupSubmit(event, this);
				});
			}
		}
	}

	allowRemoveUpdate();

	function groupSubmit(event, quantity) {
		if (event.key !== 8 && event.key !== 37 && event.key !== 38 && event.key !== 39 && event.key !== 40 && event.key !== 46 && quantity.value !== '') {
			document.querySelector('[data-hook="' + event.target.getAttribute('data-group') + '"]').submit();
		}
	}
})();
```

**Closed** 2019-05-01 18:44 UTC
Labels: bug, enhancement, question, v1.0.5, verified
